#!/bin/bash
# =========================================
# Quick Setup | About Menu
# =========================================
clear
# Warna Standard
BlueCyan='\e[5;36m'
NC='\e[0m'
ungu='\033[0;35m'
WhiteBe='\e[5;37m'
Green="\033[92;1m"
Cyan="\033[96;1m"

# Load Info (Agar nama owner muncul)
nama=$(cat /etc/xray/username 2>/dev/null)
if [[ -z "$nama" ]]; then
  nama="Admin"
fi

# Fungsi Tampilan
function baris_panjang() {
  echo -e "\033[5;36m ◇━━━━━━━━━━━━━━━━━◇ \033[0m"
}

function Xwan_Banner() {
    clear
    baris_panjang
    echo -e "\033[95;1m     $nama       \033[0m"
    baris_panjang
}

# Fungsi List Harga Script
function List_Script() {
    echo -e "${ungu}            DAFTAR SEWA SCRIPT            ${NC}"
    baris_panjang
    echo ""
    echo -e "${Cyan}"
    echo " 1 bulan  / 1 ip    : 10.000 "
    echo " 2 bulan  / 2 ip    : 20.000 "
    echo " Lifetime / 1 ip    : 30.000 "
    echo " Lifetime / 2 ip    : 45.000 "
    echo " Lifetime / 3 ip    : 60.000 "
    echo " Lifetime / 4 ip    : 75.000 "
    echo " Lifetime / 5 ip    : 100.000 "
    echo " Lifetime / Unli ip : 150.000 "
    echo ""
    echo -e "${NC}"
    baris_panjang
}

# Fungsi List Source Code
function List_Source() {
    echo -e "${Cyan}"
    echo " OPEN SOURCE : 800.000 "
    echo -e "${NC}"
    baris_panjang
    echo ""
    echo -e "${WhiteBe}"
    echo " Keuntungan beli Open Source: "
    echo ""
    echo " - Script jadi hak Milik 100% "
    echo " - Script Bisa disewakan "
    echo " - Script Bebas Edit / Custom "
    echo -e "${NC}"
    echo ""
    echo -e "${BlueCyan} Thanks, SMART TECNO ${NC} "
    echo ""
    baris_panjang
}

# --- Tampilan Utama ---
Xwan_Banner
echo -e "${BlueCyan}                  ABOUT                   ${NC}"
baris_panjang
echo ""
echo -e "${Green}"
echo " Jika Anda Minat dengan Sc Kami "
echo " Boleh anda Hubungi nomor di bawah "
echo " Whatsapp : 6282241967317 "
echo -e "${NC}"
baris_panjang
echo -e " "
List_Script
echo ""
List_Source
echo -e " "

read -n 1 -s -r -p "Press [ Enter ] to back to menu"
menu