#!/bin/bash

g="\e[92;1m"
RED="\033[31m"
NC='\033[0m'
y='\033[1;93m'
gg='\e[1;77m'
ungu="\033[0;35m"
PURPLE='\033[35m'
PURPLE_BOLD='\033[1;35m'
BG_BLU="\033[44;1m" # BG BIRU
clear
touch /root/.system
data1=( `awk -F: '$3 >= 1000 && $1 != "nobody" {print $1}' /etc/passwd `)
for user in "${data1[@]}"
do
dir="/etc/kyt/limit/ssh/ip"
iplimit1="$dir/$user"

# Cek apakah direktori ada, jika tidak buat direktori
if [[ ! -d $dir ]]; then
    mkdir -p $dir
fi

# Cek apakah file ada dan tidak kosong, jika tidak, tulis data "2"
if [[ ! -f $iplimit1 || ! -s $iplimit1 ]]; then
    echo "2" > $iplimit1
fi
done
clear
echo -e "  ${PURPLE}───────────────────────────────────────${NC}"
echo -e "  ${BG_BLU}             USER LOGIN SSH            ${NC}  ️"
echo -e "  ${PURPLE}───────────────────────────────────────${NC}"
echo -e "     LOGIN IP    LIMIT IP    USERNAME "
mulog=$(cekssh)
data=( `awk -F: '$3 >= 1000 && $1 != "nobody" {print $1}' /etc/passwd`)
for user in "${data[@]}"
do
cekcek=$(echo -e "$mulog" | grep -wE $user | wc -l)
if [[ $cekcek -gt 0 ]]; then
iplimit=$(cat /etc/kyt/limit/ssh/ip/$user)
printf "  %-13s %-7s %-8s %2s\n" "     ${cekcek} IP        ${iplimit} IP      ${user}"
echo "slot" >> /root/.system
else
echo > /dev/null
fi
echo send_log > /dev/null
done
aktif=$(cat /root/.system | wc -l)
echo -e "  ${PURPLE}───────────────────────────────────────${NC}"
echo -e "            $aktif User Online"
echo -e "  ${PURPLE}───────────────────────────────────────${NC}"
sed -i "d" /root/.system
