#!/bin/bash
# COLOR VALIDATION
clear
RED='\033[0;31m'
NC='\e[0m'
gray="\e[1;30m"
Blue="\033[1;36m"
GREEN='\033[0;32m'
grenbo="\033[1;95m"
YELL='\033[1;33m'
BGX="\033[42m"
UPDATE="https://abc.xcodehoster.com/"
BOT="https://abc.xcodehoster.com/"
ipsaya=$(curl -sS ipv4.icanhazip.com)
data_server=$(curl -v --insecure --silent https://google.com/ 2>&1 | grep Date | sed -e 's/< Date: //')
date_list=$(date +"%Y-%m-%d" -d "$data_server")
data_ip="https://https://raw.githubusercontent.com/ica4me/auto-script-free/main/romsip"
checking_sc() {
  useexp=$(wget -qO- $data_ip | grep $ipsaya | awk '{print $3}')
  if [[ $date_list < $useexp ]]; then
    echo -ne
  else
   echo -e "\033[1;93m────────────────────────────────────────────\033[0m"
        echo -e "\033[41;1m ⚠️       AKSES DI TOLAK         ⚠️ \033[0m"
        echo -e "\033[1;93m────────────────────────────────────────────\033[0m"
        echo -e ""
        echo -e "        \033[91;1m❌ SCRIPT LOCKED ❌\033[0m"
        echo -e ""
        echo -e "  \033[0;33m🔒 Your VPS\033[0m $MYIP \033[0;33mHas been Banned\033[0m"
        echo -e ""
        echo -e "  \033[91m⚠️  Masa Aktif Sudah Habis ⚠️\033[0m"
        echo -e "  \033[0;33m💡 Beli izin resmi hanya dari Admin!\033[0m"
        echo -e ""
        echo -e "  \033[92;1m📞 Contact Admin:\033[0m"
        echo -e "  \033[96m📱 WhatsApp: https://wa.me/6282241967317\033[0m"
        echo -e ""
        echo -e "\033[1;93m────────────────────────────────────────────\033[0m"
    exit
  fi
}
checking_sc

echo -e "\033[96m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo -e " \e[1;971m                      MENU BOT                \e[0m"
echo -e "\033[96m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo -e "  ${grenbo}[1]${NC}${YELL} Add Bot Notifikasi${NC}"
echo -e "  ${grenbo}[2]${NC}${YELL} Delete Bot Notifikasi${NC}"
echo -e "  ${grenbo}[0]${NC}${YELL} Back To Menu${NC}"
echo -e ""
read -p "  Select From Options [ 1 - 2 or 0 ] : " menu
case $menu in
1) clear ;
    add-bot-notif
    ;;
2) clear ;
    del-bot-notif
    ;;
0) clear ;
    menu
    ;;
*) clear ;
    menu
    ;;
esac
