#!/bin/bash

yellow="\033[0;33m"
ungu="\033[0;35m"
Red="\033[91;1m"
Xark="\033[0m"
BlueCyan="\033[5;36m"
WhiteBe="\033[5;37m"
GreenBe="\033[5;32m"
YellowBe="\033[5;33m"
BlueBe="\033[5;34m"
nama=$(cat /etc/xray/username)

# Garis Ungu
function baris_panjang() {
  echo -e "${ungu} ——————————————————————————————————— ${Xark}"
}

# Banner
function Xwan_Banner() {
  clear
  baris_panjang
  echo -e "${BlueCyan}           $nama      ${Xark}"
  baris_panjang
}

# Credit
function Sc_Credit() {
  sleep 1
  baris_panjang
  echo -e "${BlueCyan}  Terimakasih Telah Menggunakan ${Xark}"
  echo -e "${BlueCyan}          Script Credit ${Xark}"
  echo -e "${BlueCyan}          $nama ${Xark}"
  baris_panjang
  exit 1
}

# Animasi Loading
duration=6
frames=("██10%" "█████35%" "█████████65%" "█████████████80%" "█████████████████████90%" "█████████████████████████100%")
num_frames=${#frames[@]}
num_iterations=$((duration))

Loading_Animasi() {
  for ((i = 0; i < num_iterations; i++)); do
    clear
    index=$((i % num_frames))
    color_code=$((31 + i % 7))
    echo ""
    echo ""
    echo ""
    echo -e "\e[1;${color_code}m ${frames[$index]}\e[0m"
    sleep 0.5
  done
}

Loading_Succes() {
  clear
  echo -e  "\033[5;32mSucces\033[0m"
  sleep 2
  clear
}

# List User VLESS
function Daftar_User_Vless() {
  grep -E "^#& " "/etc/xray/config.json" | cut -d ' ' -f 2-3 | sort -u
}

# Main Script
clear
Xwan_Banner
baris_panjang
echo -e "${WhiteBe} Daftar User VLESS:${Xark}"
baris_panjang

mapfile -t users < <(Daftar_User_Vless)

if [[ ${#users[@]} -eq 0 ]]; then
  echo -e "${Red}Tidak ada user ditemukan!${Xark}"
  Sc_Credit
fi

for i in "${!users[@]}"; do
  nomor=$((i+1))
  user=$(echo "${users[$i]}" | awk '{print $1}')
  exp=$(echo "${users[$i]}" | awk '{print $2}')
  echo -e "${yellow}$nomor${Xark}. ${WhiteBe}$user${Xark}  (Expired: $exp)"
done

baris_panjang
echo ""
read -p "Pilih nomor user: " pilih

if [[ -z "$pilih" || "$pilih" -lt 1 || "$pilih" -gt ${#users[@]} ]]; then
  echo -e "${Red}Pilihan tidak valid!${Xark}"
  Sc_Credit
fi

user=$(echo "${users[$((pilih-1))]}" | awk '{print $1}')
limit_file="/etc/kyt/limit/vless/ip/${user}"

if [ -e "$limit_file" ]; then
  current_iplimit=$(cat "$limit_file")
  Xwan_Banner
  baris_panjang
  echo -e "${WhiteBe}Limit IP User ${user}: ${current_iplimit}${Xark}"
  baris_panjang
  echo ""
  read -p "Input New IP: " new_iplimit
  baris_panjang
  echo ""

  Loading_Animasi
  Loading_Succes

  if [ -z "$new_iplimit" ]; then
    Xwan_Banner
    baris_panjang
    echo -e "${Red}GAGAL !!${Xark}"
    baris_panjang
    Sc_Credit
  else
    echo "$new_iplimit" > "$limit_file"
    Xwan_Banner
    baris_panjang
    echo -e "${GreenBe}Successfully Updated${Xark}"
    echo ""
    echo -e "${yellow}New IP Limit : $new_iplimit${Xark}"
    echo -e "${yellow}Username     : $user${Xark}"
    baris_panjang
    Sc_Credit
  fi
else
  echo -e "${Red}File batasan IP tidak ditemukan untuk user $user.${Xark}"
  Sc_Credit
fi
