#!/bin/bash
# ==========================================
# Color
NC='\e[0m'
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[0;33m'
BLUE='\033[0;34m'
PURPLE='\033[0;35m'
CYAN='\033[0;36m'

# Efek tambahan
BLINK_GREEN="\033[5;32m"
BLINK_RED="\033[5;31m"

# Background
BG_BLU="\033[44;1m" # BG BIRU
# ==========================================

nama=$(cat /etc/xray/username 2>/dev/null || echo "Script-Xwan")

# Fungsi garis
function baris_panjang() {
  echo -e "${PURPLE}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
}

# Banner
function Xwan_Banner() {
clear
baris_panjang
echo -e " ${BG_BLU}                 $nama                     ${NC}"
baris_panjang
}

# Credit
function Sc_Credit(){
sleep 1
baris_panjang
echo -e "${CYAN}   Terimakasih Telah Menggunakan Script ${NC}"
echo -e "${CYAN}             Powered By $nama ${NC}"
baris_panjang
exit 1
}

# Animasi loading
frames=("██10%" "█████35%" "█████████65%" "█████████████80%" "█████████████████████90%" "█████████████████████████100%")

Loading_Animasi() {
    for frame in "${frames[@]}"; do
        clear
        echo -e "\n\n\n\e[1;36m $frame\e[0m"
        sleep 0.4
    done
}

Loading_Succes() {
clear
echo -e  "${BLINK_GREEN}Succes${NC}"
sleep 1
clear
}

# ========================= MAIN =========================
Xwan_Banner
echo -e "${PURPLE}┌───────────────────────────────────────────────┐${NC}"
echo " No  USERNAME           EXP DATE         STATUS"
echo -e "${PURPLE}└───────────────────────────────────────────────┘${NC}"

i=0
declare -A user_list
while read expired
do
  AKUN="$(echo $expired | cut -d: -f1)"
  ID="$(echo $expired | grep -v nobody | cut -d: -f3)"
  exp="$(chage -l $AKUN | grep "Account expires" | awk -F": " '{print $2}')"
  status="$(passwd -S $AKUN | awk '{print $2}' )"
  if [[ $ID -ge 1000 ]]; then
    i=$((i+1))
    user_list[$i]=$AKUN
    if [[ "$status" = "P" ]]; then
      printf "%-3s %-17s %-20s %-10s\n" "[$i]" "$AKUN" "$exp" "UNLOCKED"
    else
      printf "%-3s %-17s %-20s %-10s\n" "[$i]" "$AKUN" "$exp" "LOCKED"
    fi
  fi
done < /etc/passwd

JUMLAH=$i

echo -e "${PURPLE}┌───────────────────────────────────────────────┐${NC}"
echo "   Total Account: $JUMLAH user"
echo -e "${PURPLE}└───────────────────────────────────────────────┘${NC}"
echo ""

read -p "Pilih nomor user yang ingin di-lock: " num

username=${user_list[$num]}

if [[ -z "$username" ]]; then
    clear
    Xwan_Banner
    baris_panjang
    echo -e "${BLINK_RED} Pilihan tidak valid! ${NC}"
    baris_panjang
    exit 1
fi

# Proses lock
Loading_Animasi
Loading_Succes

passwd -l $username &>/dev/null
clear
Xwan_Banner
baris_panjang
echo -e "${BLINK_GREEN}   Succesfully Locked ${NC}"
echo -e ""
echo -e "${YELLOW} Username  : $username ${NC}"
echo -e "${RED} Status    : LOCKED!! ${NC}"
echo -e ""
baris_panjang
Sc_Credit
