#!/bin/bash
# ==========================================
# Color
RED='\033[0;31m'
NC='\033[0m'
GREEN='\033[0;32m'
CYAN='\033[0;36m'
BlueCyan='\e[5;36m'
Xark='\e[0m'
ungu='\e[35m'
yellow='\e[33m'
WhiteBe='\e[5;37m'
GreenBe='\e[5;32m'
Cyan="\033[96;1m"
PURPLE='\033[0;35m'

# Efek tambahan
BLINK_GREEN="\033[5;32m"
BLINK_RED="\033[5;31m"

# Background
BG_BLU="\033[44;1m" # BG BIRU
# ==========================================
# Get Bot
CHATID=$(grep -E "^#bot# " "/etc/bot/.bot.db" | cut -d ' ' -f 3)
KEY=$(grep -E "^#bot# " "/etc/bot/.bot.db" | cut -d ' ' -f 2)
export TIME="10"
export URL="https://api.telegram.org/bot$KEY/sendMessage"

# Getting server info
MYIP=$(curl -sS ipv4.icanhazip.com)
nama=$(cat /etc/xray/username)
ISP=$(cat /etc/xray/isp)
CITY=$(cat /etc/xray/city)
domain=$(cat /etc/xray/domain)

# ================= Banner & Liner =================
function baris_panjang() {
  echo -e "${PURPLE}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
}

function Xwan_Banner() {
clear
baris_panjang
echo -e "${BG_BLU}                  $nama                    ${NC}"
baris_panjang
}

function Sc_Credit(){
sleep 1
baris_panjang
echo -e "${CYAN}  Terimakasih Telah Menggunakan ${NC}"
echo -e "${CYAN}          Script Credit ${NC}"
echo -e "${CYAN}          $nama ${NC}"
baris_panjang
exit 1
}

# ================= Loading Anim =================
Loading_Animasi() {
frames=("██10%" "█████35%" "█████████65%" "█████████████80%" "█████████████████████90%" "█████████████████████████100%")
duration=6
num_frames=${#frames[@]}
num_iterations=$((duration))
for ((i=0;i<num_iterations;i++)); do
  clear
  index=$((i % num_frames))
  color_code=$((31 + i % 7))
  echo -e "\n\n\n\e[1;${color_code}m ${frames[$index]}\e[0m"
  sleep 0.5
done
}

Loading_Succes() {
clear
echo -e  "\033[5;32mSuccess\033[0m"
sleep 1
clear
}

# ================= Tampilkan Daftar User =================
Xwan_Banner
echo -e "${PURPLE}┌───────────────────────────────────────────────┐${NC}"
echo " No  USERNAME           EXP DATE         STATUS"
echo -e "${PURPLE}└───────────────────────────────────────────────┘${NC}"
echo -e "${PURPLE}┌───────────────────────────────────────────────┐${NC}"

i=0
declare -A USERS
while IFS=: read -r AKUN _ _ ID _; do
  if [[ $ID -ge 1000 && $AKUN != "nobody" ]]; then
    i=$((i+1))
    exp=$(chage -l "$AKUN" | grep "Account expires" | awk -F": " '{print $2}')
    status=$(passwd -S "$AKUN" | awk '{print $2}')
    USERS[$i]=$AKUN
    if [[ "$status" = "L" ]]; then
        stat_txt="LOCKED"
    else
        stat_txt="UNLOCKED"
    fi
    printf "  [%-2d] %-17s %-17s %s\n" $i "$AKUN" "$exp" "$stat_txt"
  fi
done < /etc/passwd

echo -e "${PURPLE}└───────────────────────────────────────────────┘${NC}"
echo -e "Pilih nomor user yang ingin dilihat detailnya: "
read -rp "Input No : " nomor

if [[ -z $nomor || -z ${USERS[$nomor]} ]]; then
  echo -e "${RED}User Tidak Ditemukan!!!${NC}"
  read -n 1 -s -r -p "Enter Back To Menu"
  m-ssh
fi

# ================= Ambil Detail =================
user=${USERS[$nomor]}
sleep 2 & Loading_Animasi

Login=$(grep -wE $user /etc/ssh/.ssh.db | awk '{print $2}')
Pass=$(grep -wE $user /etc/ssh/.ssh.db | awk '{print $3}')
Quota=$(grep -wE $user /etc/ssh/.ssh.db | awk '{print $4}')
iplimit=$(grep -wE $user /etc/ssh/.ssh.db | awk '{print $5}')
expe=$(grep -wE $user /etc/ssh/.ssh.db | awk '{print $6" "$7" "$8}')

PAYLOADWS="GET / HTTP/1.1[crlf]Host: [host][crlf]Connection: Upgrade[crlf]User-Agent: [ua][crlf]Upgrade: websocket[crlf][crlf]"
PAYLOADTLS="GET wss://$domain/ HTTP/1.1[crlf]Host: [host][crlf]Connection: Upgrade[crlf]User-Agent: [ua][crlf]Upgrade: websocket[crlf][crlf]"
PAYLOADHANCED="HEAD / HTTP/1.1[crlf]Host: Masukan_Bug[crlf][crlf]PATCH / HTTP/1.1[crlf]Host: [host][crlf]Upgrade: websocket[crlf][crlf][split]HTTP/ 1[crlf][crlf]"

# ================= Function =================
function Send_Log() {
TEXT="
<code>◇━━━━━━━━━━━━━━━━━◇</code>
<code>SSH OVPN Account     </code>
<code>◇━━━━━━━━━━━━━━━━━◇</code>
<code>Username         : </code> <code>$Login</code>
<code>Password         : </code> <code>$Pass</code>
<code>Limit Quota      : </code> <code>$Quota</code>
<code>◇━━━━━━━━━━━━━━━━━◇</code>
<code>IP               : $IP</code>
<code>Host             : </code> <code>$domain</code>
<code>Port OpenSSH     : 443, 80, 22</code>
<code>Port Dropbear    : 443, 109</code>
<code>Port SSH WS      : 80, 8080, 8081-9999 </code>
<code>Port SSH UDP     : 1-65535 </code>
<code>Port SSH SSL WS  : 443</code>
<code>Port SSL/TLS     : 400-900</code>
<code>Port OVPN WS SSL : 443</code>
<code>Port OVPN SSL    : 443</code>
<code>Port OVPN TCP    : 443, 1194</code>
<code>Port OVPN UDP    : 2200</code>
<code>BadVPN UDP       : 7100, 7300, 7300</code>
<code>◇━━━━━━━━━━━━━━━━━◇</code>
OVPN Download : https://$domain:81/
<code>Save Link Account: </code>https://$domain:81/ssh-$Login.txt
<code>Berakhir Pada        : $expe</code>
"
curl -s --max-time $TIME -d "chat_id=$CHATID&disable_web_page_preview=1&text=$TEXT&parse_mode=html" $URL >/dev/null
}

# ================= Show Detail =================
function Details_Ssh(){
Xwan_Banner
echo -e "  \033[37;1;7mSSH OPENVPN\033[0m"
baris_panjang
echo -e "${CYAN} Remark      : $Login ${NC}"
echo -e "${CYAN} Password    : $Pass ${NC}"
echo -e "${CYAN} Limit Quota : $Quota ${NC}"
echo -e "${CYAN} Limit Ip    : ${iplimit} Devic ${NC}"
echo -e "${CYAN} Domain      : $domain ${NC}"
echo -e "${CYAN} ISP         : $ISP ${NC}"
echo -e "${CYAN} OpenSSH     : 443, 80, 22 ${NC}"
echo -e "${CYAN} Port UDP    : 1-65535 ${NC}"
echo -e "${CYAN} SSH WS      : 80,8080,8880,2082 ${NC}"
echo -e "${CYAN} SSL/TLS     : 443 ${NC}"
echo -e "${CYAN} OVPN UDP    : 2200 ${NC}"
baris_panjang
}

function Copy_Faste(){
echo -e "${CYAN} Port 80     : $domain:80@$Login:$Pass ${NC}"
echo -e "${CYAN} Port 443    : $domain:443@$Login:$Pass ${NC}"
echo -e "${CYAN} Udp Custom  : $domain:1-65535@$Login:$Pass${NC}"
echo -e "${CYAN} OpenVpn     : https://$domain:81/ ${NC}"
echo -e "${CYAN} Account     : https://$domain:81/ssh-$Login.txt ${NC}"
}

function Details_Payload(){
baris_panjang
echo -e "${CYAN} Payload WS  : ${PAYLOADWS} ${NC}"
baris_panjang
echo -e "${CYAN} Payload TLS : ${PAYLOADTLS} ${NC}"
baris_panjang
echo -e "${CYAN} Payload ENCD: ${PAYLOADHANCED} ${NC}"
baris_panjang
}

function Expiry_Details(){
echo -e "${yellow} Expiry in  : $expe ${NC}"
}

# ================= Run =================
Xwan_Banner
Details_Ssh
Copy_Faste
Details_Payload
Expiry_Details
Send_Log
Sc_Credit
read -n 1 -s -r -p "Enter Back To Menu"
m-ssh
